backend:
  # Change this to 'test-repo' if
  # doing any testing in development
  # otherwise leave it as 'git-gateway'
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

display_url: https://glvn.co

collections:
  - name: "blog"
    label: "Blog"
    folder: "cms/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: cms/pages/index.md
        label: "Home Page"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "PageContent", name: "pageContent", widget: "markdown" }

      - file: cms/pages/about.md
        label: "About Page"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "PageContent", name: "pageContent", widget: "markdown" }

      - file: cms/pages/projects.md
        label: "Projects Page"
        name: "projects"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "projects-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Top Content", name: "topContent", widget: "markdown" }
          - {
              label: "Projects",
              name: projectList,
              widget: "list",
              fields:
                [
                  {
                    label: "Project Name",
                    name: "projectName",
                    widget: string,
                  },
                  {
                    label: "Project Description",
                    name: "projectDesc",
                    widget: string,
                  },
                  {
                    label: "Project Web URL",
                    name: "projectLinks",
                    widget: list,
                    fields:
                      [
                        {
                          label: "Link Name",
                          name: "linkName",
                          widget: string,
                        },
                        {
                          label: "Link URL",
                          name: "linkHref",
                          widget: "string",
                        },
                      ],
                  },
                ],
            }
          - { label: "Bottom Text", name: "bottomContent", widget: "markdown" }

      - file: cms/pages/contact.md
        label: "Contact Page"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Top Content", name: "pageContent", widget: "markdown" }

      - file: cms/pages/links.md
        label: "Links Page"
        name: "links"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "links-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Top Content", name: "pageContent", widget: "markdown" }

  - name: "components"
    label: "Components"
    files:
      - file: cms/components/contact-info.md
        label: "Contact Info"
        name: "contact-info"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Resume", name: "resume", widget: "string" }
          - { label: "Github", name: "github", widget: "string" }
          - { label: "LinkedIn", name: "linkedin", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
          - { label: "Medium", name: "medium", widget: "string" }
          - { label: "Dev.to", name: "dev", widget: "string" }

      - file: cms/components/header.md
        label: "Header"
        name: "header"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - {
              label: "Header Links",
              name: "headerLinks",
              widget: "list",
              fields:
                [
                  { label: "Link Name", name: "linkName", widget: "string" },
                  { label: "Link Value", name: "linkHref", widget: "string" },
                  { label: "Link Alt", name: "linkAlt", widget: "string" },
                  {
                    label: "Link Type",
                    name: "linkType",
                    widget: "select",
                    options: ["external", "internal"],
                    default: "internal",
                  },
                  {
                    label: "Enabled in Production?",
                    name: "enabled",
                    widget: "select",
                    options: ["false", "true"],
                    default: "false",
                  },
                ],
            }
